version: '3'
 
services:
 
   node:
     build:
        context: .
        dockerfile: Dockerfile
     command: "yarn run serve"
     ports:
       - "${NODE_PORT:-8080}:8080"
     volumes:
       - ".:/app"